export const paths = [
  {
    id: "ebook",
    title: "SOLO SYSTEM · El Ebook",
    subtitle: "Lanzamiento & Comunidad",
    icon: "📕",
    color: "cyan",
    gradient: "from-cyan-400 to-blue-600",
    hex: "#22d3ee",
    goal: "Lanzar el ebook, crear comunidad en IG y monetizar con el avatar interactivo.",
    status: "PUBLICADO · Fase comunidad",
  },
  {
    id: "vet",
    title: "VETERINARIA · El Oficio",
    subtitle: "Curso IPS + Prácticas + Trabajo",
    icon: "🩺",
    color: "emerald",
    gradient: "from-emerald-400 to-teal-600",
    hex: "#10b981",
    goal: "Terminar los 2 libros restantes, hacer prácticas y conseguir empleo fijo en España.",
    status: "LIBRO 4/6 · Restan 2",
  },
  {
    id: "code",
    title: "PROGRAMACIÓN · El Hobby",
    subtitle: "Web & App Solo System",
    icon: "💻",
    color: "violet",
    gradient: "from-violet-400 to-fuchsia-600",
    hex: "#8b5cf6",
    goal: "Dominar IA + no-code + código; terminar la app Solo System tras el lanzamiento.",
    status: "ESTE ES TU DESK · CREADOR",
  },
];

export const neuroPrinciples = [
  {
    title: "Pomodoro 25/5",
    icon: "⏱️",
    desc: "El cerebro consolida foco en bloques cortos. Usa 25 min de deep work + 5 de descanso activo.",
    science: "Corteza prefrontal: fatiga tras ~25 min de atención sostenida.",
  },
  {
    title: "Spaced Repetition",
    icon: "🔁",
    desc: "Repasa el libro de veterinaria a los 1, 3, 7 y 21 días. Usa flashcards (Anki gratis).",
    science: "Curva del olvido de Ebbinghaus: sin repaso pierdes 70% en 24h.",
  },
  {
    title: "Interleaving",
    icon: "🔀",
    desc: "Alterna los 3 proyectos en el mismo día. Tu cerebro los refuerza mutuamente.",
    science: "Mezclar materias mejora transferencia un 43% vs estudio en bloque.",
  },
  {
    title: "Active Recall",
    icon: "🧠",
    desc: "No releas pasivamente. Cierra el libro y explica en voz alta lo aprendido.",
    science: "Recuperar activa el hipocampo 3x más que la relectura.",
  },
  {
    title: "Sleep Consolidation",
    icon: "🌙",
    desc: "Dormir 7-8h no es lujo: es cuando tu cerebro graba lo aprendido del día.",
    science: "Durante sueño REM se transfiere info del hipocampo a la neocorteza.",
  },
  {
    title: "Dopamine Stacking",
    icon: "⚡",
    desc: "Marca microtareas cumplidas. Cada tick libera dopamina y refuerza el hábito.",
    science: "Recompensas pequeñas y frecuentes crean circuitos de hábito duraderos.",
  },
];

export const sixMonthPlan = [
  {
    month: 1,
    title: "Despertar",
    subtitle: "Fundación del sistema",
    color: "cyan",
    hex: "#22d3ee",
    focus: "Fundación & Pre-lanzamiento",
    vet: "Terminar LIBRO 5 de IPS (1 cap/semana)",
    ebook: "Configurar IG + 9 posts de contenido + 3 Reels previos",
    code: "Que es una web: HTML estructura, etiquetas, head/body, crear tu primera pagina",
    milestone: "🎯 500 seguidores en IG y libro 5 cerrado",
  },
  {
    month: 2,
    title: "Lanzamiento",
    subtitle: "Publicar y cerrar curso",
    color: "violet",
    hex: "#8b5cf6",
    focus: "Lanzamiento & Cierre de curso",
    vet: "Terminar LIBRO 6 y solicitar prácticas",
    ebook: "Pre-lanzamiento: waitlist + 1 Reel cada 3 días + LANZAMIENTO",
    code: "CSS desde cero: colores, fuentes, layout, flexbox, responsive y Tailwind basico",
    milestone: "🎯 Ebook publicado y libro 6 terminado",
  },
  {
    month: 3,
    title: "Prácticas",
    subtitle: "Clínica real y tracción",
    color: "emerald",
    hex: "#10b981",
    focus: "Prácticas & Tracción",
    vet: "Iniciar prácticas gratuitas en Jaén",
    ebook: "Campaña de testimonios + 1ª oferta flash",
    code: "JavaScript desde cero: variables, funciones, arrays, eventos y DOM",
    milestone: "🎯 10h/semana de clínica real + app en beta",
  },
  {
    month: 4,
    title: "Monetización",
    subtitle: "Profundizar e ingresos",
    color: "rose",
    hex: "#f43f5e",
    focus: "Profundizar & Monetizar",
    vet: "Mitad de prácticas · pedir referencias",
    ebook: "2ª edición con bonus · upsell del avatar",
    code: "React desde cero: componentes, props, estado, useEffect y primera app",
    milestone: "🎯 Primeros ingresos recurrentes del ebook",
  },
  {
    month: 5,
    title: "Integración",
    subtitle: "Trabajo y escala",
    color: "amber",
    hex: "#f59e0b",
    focus: "Integración laboral",
    vet: "Terminar prácticas + entrevistas de trabajo",
    ebook: "Colaboraciones con 3 cuentas grandes",
    code: "TypeScript + localStorage + formularios + tu primera app completa",
    milestone: "🎯 Contrato de asistente veterinario firmado",
  },
  {
    month: 6,
    title: "Estabilidad",
    subtitle: "Consolidar y escalar",
    color: "fuchsia",
    hex: "#d946ef",
    focus: "Estabilidad & Escala",
    vet: "Trabajo fijo + empezar inglés formal",
    ebook: "Comunidad pagada (Discord premium)",
    code: "Backend basico (Supabase) + deploy en Vercel + app publica con URL",
    milestone: "👑 3 pilares activos sin sacrificar ninguno",
  },
];

export const dailySchedule = [
  { time: "07:30", block: "🌅 Despertar + hidratación + luz solar", type: "reset", min: 30 },
  { time: "08:00", block: "📓 Journal 10 min · Intención del día (3 metas)", type: "mindset", min: 15 },
  { time: "08:15", block: "💪 Calistenia (L-V · 90 min)", type: "body", min: 90 },
  { time: "09:45", block: "🚿 Ducha + desayuno proteico", type: "reset", min: 45 },
  { time: "10:30", block: "🩺 Veterinaria · Estudio enfocado (Pomodoro 25/5 × 4)", type: "vet", min: 120 },
  { time: "12:30", block: "🧠 Active Recall · Explica lo aprendido en voz alta", type: "vet", min: 20 },
  { time: "12:50", block: "🍽️ Comida + descanso digestivo (sin pantallas)", type: "reset", min: 70 },
  { time: "14:00", block: "🩺 Veterinaria · Flashcards Anki + test del libro", type: "vet", min: 60 },
  { time: "15:00", block: "📕 Ebook · Contenido y comunidad", type: "ebook", min: 120 },
  { time: "17:00", block: "☕ Pausa + caminata 15 min", type: "reset", min: 20 },
  { time: "17:20", block: "📱 Creación IG · 1 Reel o 1 carrusel del día", type: "ebook", min: 40 },
  { time: "18:00", block: "💻 Programación · Código y aprendizaje", type: "code", min: 120 },
  { time: "20:00", block: "🍽️ Cena ligera", type: "reset", min: 60 },
  { time: "21:00", block: "🌙 Inglés 20 min (Duolingo) · solo si hay energía", type: "bonus", min: 20 },
  { time: "21:20", block: "📓 Review del día · marca progreso · planifica mañana", type: "mindset", min: 20 },
  { time: "21:40", block: "😴 Rutina de sueño · sin pantallas", type: "reset", min: 80 },
];




